include:
  - project: 'katagena/projects'
    ref: master
    file: 'playbooks/roles/templating/templates/generic/gitlabci.auto-devops.yml'

build-latest:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build --pull --build-arg CI_PROJECT_URL=$CI_PROJECT_URL -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

pages:
  stage: production
  image: $CI_REGISTRY_IMAGE
  script:
    - cp -R /usr/share/nginx/html/ public/
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
