include:
  - project: 'katagena/templates'
    file: 'ci/global.yml'

build:
  stage: build
  image: alpine:latest
  script:
    - apk --update add make
    - ./kobe-fetch.sh
    - cp -R web/ public/
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
    